[2023-08-08T03:49:02.437+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: our_dag_with_python_operator_v07.greet scheduled__2022-01-04T00:00:00+00:00 [queued]>
[2023-08-08T03:49:02.451+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: our_dag_with_python_operator_v07.greet scheduled__2022-01-04T00:00:00+00:00 [queued]>
[2023-08-08T03:49:02.457+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 6
[2023-08-08T03:49:02.475+0000] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): greet> on 2022-01-04 00:00:00+00:00
[2023-08-08T03:49:02.479+0000] {standard_task_runner.py:57} INFO - Started process 2026 to run task
[2023-08-08T03:49:02.492+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'our_dag_with_python_operator_v07', 'greet', 'scheduled__2022-01-04T00:00:00+00:00', '--job-id', '324', '--raw', '--subdir', 'DAGS_FOLDER/simple_print.py', '--cfg-path', '/tmp/tmpto_1wdyf']
[2023-08-08T03:49:02.506+0000] {standard_task_runner.py:85} INFO - Job 324: Subtask greet
[2023-08-08T03:49:02.579+0000] {task_command.py:410} INFO - Running <TaskInstance: our_dag_with_python_operator_v07.greet scheduled__2022-01-04T00:00:00+00:00 [running]> on host e301933437eb
[2023-08-08T03:49:02.709+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='coder2j' AIRFLOW_CTX_DAG_ID='our_dag_with_python_operator_v07' AIRFLOW_CTX_TASK_ID='greet' AIRFLOW_CTX_EXECUTION_DATE='2022-01-04T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2022-01-04T00:00:00+00:00'
[2023-08-08T03:49:02.711+0000] {logging_mixin.py:150} INFO - some dict:  {'a': 1, 'b': 2}
[2023-08-08T03:49:02.770+0000] {logging_mixin.py:150} INFO - Hello World! My name is Jerry Fridman, and I am 19 years old!
[2023-08-08T03:49:02.773+0000] {python.py:183} INFO - Done. Returned value was: None
[2023-08-08T03:49:02.781+0000] {local_task_job_runner.py:115} ERROR - Received SIGTERM. Terminating subprocesses
[2023-08-08T03:49:02.806+0000] {process_utils.py:135} INFO - Sending Signals.SIGTERM to group 2026. PIDs of all processes in the group: [2026]
[2023-08-08T03:49:02.807+0000] {process_utils.py:86} INFO - Sending the signal Signals.SIGTERM to group 2026
[2023-08-08T03:49:02.852+0000] {taskinstance.py:1517} ERROR - Received SIGTERM. Terminating subprocesses.
[2023-08-08T03:49:02.896+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1409, in _run_raw_task
    self.refresh_from_db(lock_for_update=True, session=session)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 73, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 807, in refresh_from_db
    for attempt in run_with_db_retries(logger=self.log):
  File "/home/airflow/.local/lib/python3.7/site-packages/tenacity/__init__.py", line 347, in __iter__
    do = self.iter(retry_state=retry_state)
  File "/home/airflow/.local/lib/python3.7/site-packages/tenacity/__init__.py", line 314, in iter
    return fut.result()
  File "/usr/local/lib/python3.7/concurrent/futures/_base.py", line 428, in result
    return self.__get_result()
  File "/usr/local/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 809, in refresh_from_db
    ti: TaskInstance | None = qry.with_for_update().one_or_none()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 2850, in one_or_none
    return self._iter().one_or_none()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 2919, in _iter
    execution_options={"_sa_orm_load_options": self.load_options},
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 1716, in execute
    conn = self._connection_for_bind(bind)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 1556, in _connection_for_bind
    engine, execution_options
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 750, in _connection_for_bind
    conn = bind.connect()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 3325, in connect
    return self._connection_cls(self, close_with_result=close_with_result)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 96, in __init__
    else engine.raw_connection()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 3404, in raw_connection
    return self._wrap_pool_connect(self.pool.connect, _connection)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 3371, in _wrap_pool_connect
    return fn()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 327, in connect
    return _ConnectionFairy._checkout(self)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 894, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 493, in checkout
    rec = pool._do_get()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/impl.py", line 256, in _do_get
    return self._create_connection()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 273, in _create_connection
    return _ConnectionRecord(self)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 388, in __init__
    self.__connect()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 691, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 72, in __exit__
    with_traceback=exc_tb,
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 686, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/create.py", line 574, in connect
    return dialect.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 598, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.7/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1519, in signal_handler
    raise AirflowException("Task received SIGTERM signal")
airflow.exceptions.AirflowException: Task received SIGTERM signal
[2023-08-08T03:49:02.983+0000] {taskinstance.py:1350} INFO - Marking task as UP_FOR_RETRY. dag_id=our_dag_with_python_operator_v07, task_id=greet, execution_date=20220104T000000, start_date=20230808T034902, end_date=20230808T034902
[2023-08-08T03:49:03.162+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 324 for task greet (Task received SIGTERM signal; 2026)
[2023-08-08T03:49:03.273+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=2026, status='terminated', exitcode=1, started='03:49:01') (2026) terminated with exit code 1
[2023-08-08T03:49:03.276+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 143
[2023-08-08T03:49:03.347+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-08-08T03:49:04.691+0000] {local_task_job_runner.py:115} ERROR - Received SIGTERM. Terminating subprocesses
